### ISSUE TITLE
Failed to install imagemin-webpack-plugin 

### ISSUE THREAD

**Issue by kszitt** [Klathmon/imagemin-webpack-plugin#110]
operating system: win10   64bit  
error log
```bath
D:\items\react-redux-antd>npm install imagemin-webpack-plugin --save-dev

> gifsicle@4.0.1 postinstall D:\items\react-redux-antd\node_modules\gifsicle
> node lib/install.js

  ‼ connect ECONNREFUSED 151.101.228.133:443
  ‼ gifsicle pre-build test failed
  i compiling from source
  × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
'autoreconf' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���


    at Promise.all.then.arr (D:\items\react-redux-antd\node_modules\bin-build\node_modules\execa\index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN react-hot-loader@4.12.15 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-tyepscript-antd@1.0.0 No description
npm WARN react-tyepscript-antd@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@4.0.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@4.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kszitt\AppData\Roaming\npm-cache\_logs\2019-12-20T08_34_07_974Z-debug.log
```
ping 151.101.228.133, no problem connecting
``` bash 
D:\items\react-redux-antd>ping 151.101.228.133

正在 Ping 151.101.228.133 具有 32 字节的数据:
来自 151.101.228.133 的回复: 字节=32 时间=123ms TTL=53
来自 151.101.228.133 的回复: 字节=32 时间=363ms TTL=53
来自 151.101.228.133 的回复: 字节=32 时间=272ms TTL=53
来自 151.101.228.133 的回复: 字节=32 时间=169ms TTL=53

151.101.228.133 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 123ms，最长 = 363ms，平均 = 231ms
```

**Comment by wellyshen** [comment]
@kszitt How did you solve this problem?

**Comment by littlegrayss** [comment]
I had the same issue, how did you resolve this?
