### ISSUE TITLE
svgo error TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by dottodot** [Klathmon/imagemin-webpack-plugin#23]
svg optimisation seem to not be working with the following

```
 new ImageminWebpackPlugin({ test: /\.(jpe?g|png|gif|svg)$/i }),
```
I get an error, but removing svg then works fine.

> TypeError: Cannot read property 'filter' of undefined
    at monkeys (/node_modules/svgo/lib/svgo/plugins.js:46:38)
    at perItem (/node_modules/svgo/lib/svgo/plugins.js:77:12)
    at /node_modules/svgo/lib/svgo/plugins.js:18:24
    at Array.forEach (native)
    at module.exports (/node_modules/svgo/lib/svgo/plugins.js:14:13)
    at /node_modules/svgo/lib/svgo.js:63:17
    at Object.sax.onend (/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/node_modules/sax/lib/sax.js:640:35)
    at end (/node_modules/sax/lib/sax.js:683:5)
    at Object.write (/node_modules/sax/lib/sax.js:991:14)
    at Object.SAXParser.close (/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/node_modules/svgo/lib/svgo/svg2js.js:169:28)
    at SVGO._optimizeOnce (/node_modules/svgo/lib/svgo.js:56:5)
    at optimizeOnceCallback (/node_modules/svgo/lib/svgo.js:42:23)
    at /node_modules/svgo/lib/svgo.js:65:9
    at Object.sax.onend (/node_modules/svgo/lib/svgo/svg2js.js:156:13)
    at emit (/node_modules/sax/lib/sax.js:640:35)
    at end (/node_modules/sax/lib/sax.js:683:5)
    at Object.write (/node_modules/sax/lib/sax.js:991:14)
    at Object.SAXParser.close (/node_modules/sax/lib/sax.js:157:38)
    at module.exports (/node_modules/svgo/lib/svgo/svg2js.js:169:28)
    at SVGO._optimizeOnce (/node_modules/svgo/lib/svgo.js:56:5)
    at SVGO.optimize (/node_modules/svgo/lib/svgo.js:49:11)
    at Promise (/node_modules/imagemin-webpack-plugin/node_modules/imagemin-svgo/index.js:19:8)
    at buf (/node_modules/imagemin-webpack-plugin/node_modules/imagemin-svgo/index.js:18:9)
    at /node_modules/promise.pipe/index.js:25:18
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Klathmon** [comment]
That looks like an error in SVGO not my library. But if you can upload the SVG that it is dying on I can take a look at the problem specifically.

**Comment by Klathmon** [comment]
You may be hitting a similar bug to the one opened [here](https://github.com/Klathmon/imagemin-webpack-plugin/issues/25). Check that to see if it fixes your problem.
