### ISSUE TITLE
Doesn't work with cross-env

### ISSUE THREAD

**Issue by ricricucit** [Klathmon/imagemin-webpack-plugin#44]
When running this plugin with [cross-env](https://www.npmjs.com/package/cross-env) I get an error coming from [cross-spawn](https://www.npmjs.com/package/cross-spawn)

using **npm@5.5.1**
using **node@v8.9.0**
using **imagemin-webpack-plugin@1.5.2** (latest at the moment of writing this issue)

```
Error: Can't find specified path.
    at notFoundError (J:\MAMP\htdocs\langhe\wp-content\themes\my-theme\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (J:\MAMP\htdocs\langhe\wp-content\themes\my-theme\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (J:\MAMP\htdocs\langhe\wp-content\themes\my-theme\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! love-langhe-template@0.1.0 prod-cross: `cross-env NODE_ENV='prod' env UV_THREADPOOL_SIZE=100 webpack -p --config webpack/webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the love-langhe-template@0.1.0 prod-cross script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\blabla\AppData\Roaming\npm-cache\_logs\2017-11-03T13_58_53_850Z-debug.log
```

See attached debug log file.
[2017-11-03T13_58_53_850Z-debug.log](https://github.com/Klathmon/imagemin-webpack-plugin/files/1441263/2017-11-03T13_58_53_850Z-debug.log)

**Comment by Klathmon** [comment]
I don't believe this is a problem with this plugin.

I'm able to use it with cross-env and cross-spawn myself fine with the given versions.

If you are able, can you provide a full webpack config that causes the problem?
