### ISSUE TITLE
v2.1.2 NPM package doesn't include `helpers.js` in `dist`

### ISSUE THREAD

**Issue by dan-rally** [Klathmon/imagemin-webpack-plugin#61]
Since v2.1.2 `helpers.js` is not included in the `dist` folder via NPM. This is causing builds to fail e.g.:

`
Error: Cannot find module './helpers.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/imagemin-webpack-plugin/dist/index.js:77:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
`

I'm not sure where the issue lies, if this is a problem with NPM. Thanks for a great package.

**Comment by Klathmon** [comment]
How the hell did that happen?

Somehow the helpers.js didn't publish with the rest of the module...

I'm sorry but bear with me while I try and figure out why helpers.js isn't being included in the published module...

**Comment by Klathmon** [comment]
Just to make sure everyone here and everyone that +1'd it gets notifications of the fix:

@dan-rally @konradhalas @LeoColomb

**Comment by konradhalas** [comment]
Thank you @Klathmon for this quick fix :)

**Comment by dan-rally** [comment]
Many thanks @Klathmon, can confirm v2.1.5 works great!
