### ISSUE TITLE
build error when i use imagemin-webpack-plugin? i dont know how to resolve 

### ISSUE THREAD

**Issue by plane-hjh** [Klathmon/imagemin-webpack-plugin#85]
![image](https://user-images.githubusercontent.com/28526327/60558278-35c2ae00-9d7b-11e9-9a82-76e5c170bf3e.png)

**Comment by Klathmon** [comment]
Are you sure it's from this plugin? I don't see anything in your image that points to an error in this plugin, but I'm more than happy to help you resolve it!

What version of webpack are you using, and are you willing to share your webpack config with me to take a look?

From looking at it, it looks like cross-spawn is throwing enoent errors, which means a file can't be found. So it could be permissions issues on your system.

**Comment by plane-hjh** [comment]
![image](https://user-images.githubusercontent.com/28526327/63988333-4d65ab00-cb0e-11e9-897f-a8a8cb74c796.png)
sorry，I only saw the information。my node version is v10.16.0，and npm version is 6.9.0。and the imagemin-webpack-plugin version is 2.4.2。

**Comment by plane-hjh** [comment]
![image](https://user-images.githubusercontent.com/28526327/63988577-83575f00-cb0f-11e9-9fc1-c7b42f408ccc.png)
this is my webpack config，i dont know what wrong

**Comment by edwardpayton** [comment]
Same error here - notFoundError for file cross-spawn/lib/enoent.js

`
Error: The system cannot find the path specified.

    at notFoundError (C:\Users\XXXXXX\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\XXXXXX\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\XXXXXX\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
`

While I can see any reference to that file in imagemin-webpack-plugin, removing it from my webpack config got rid of the error

**Comment by happy-func** [comment]
same as @edwardpayton ,where did these file go?
